apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-service
spec:
  type: NodePort
  selector:
    app: my-nextjs-app
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 3000 
      nodePort: 30080  
